### ISSUE TITLE
Synchronisation not working. Error Message

### ISSUE THREAD

**Issue by Dobbelklick** [bburky/isthereanydeal-playnite#4] opened 2024-07-23 19:57 UTC
During the Synchronisation process the following error message comes up:

```
IsThereAnyDeal Collection Sync
Sent 1 games to IsThereAnyDeal

IsThereAnyDeal response:
{"status_code":500,"reason_phrase":"Typed property IsThereAnyDeal\\Model\\Collection\\Backup\\Import\\ImportForm::$wait_remove must not be accessed before initialization"}

"added" will be reduced if games are already in collection
"copies imported" will be reduced if "ignore games already in collection" setting is used

```

Current version of Playnite and the addon is used.

**Comment by bburky** [comment] 2024-07-24 00:42
Thanks for the bug report. That's actually a PHP error message coming from the ITAD servers.

It actually looks like this is a bug in the Is There Any Deal website. I can reproduce this bug (without using my Playnite extension) at https://isthereanydeal.com/collection/import/ if I leave "Remove from Waitlist" unchecked and import a backup. I'll report this bug to ITAD via their Discord.

For now, you can work around this bug by checking "Remove from Waitlist" in the Addon settings. (I'd probably recommend checking this setting and leaving it enabled, it's nice to have ITAD automatically cleanup the waitlist when you add a game to the collection. This extension has it disabled by default to match the ITAD website behavior though.)

**Comment by bburky** [comment] 2024-07-24 14:51
This issue has been fixed by ITAD and their website has been updated. I have tested and my extension is now working again, with or without "Remove from Waitlist" enabled. No update to the extension is needed for the fix.

Please reopen this issue and leave a comment if you are still having any issues.

**Closed as completed by bburky** 2024-07-24 14:51 UTC
